### ISSUE TITLE
Épico - Portal de Notícias

### ISSUE THREAD

**Issue by Danieldcv** [aleseixas/financial_platform#11]
# Nome da história
Acesso de notícias sobre o mercado financeiro.
## Como
Investidor interessado no mercado financeiro
## Eu gostaria de
Acessar as notícias mais recentes 
## De forma que
Eu possa me manter atualizado sobre as tendências para tomar decisões sobre meus investimentos.

# Critérios de aceitação

- Verifique se as notícias são atualizadas automaticamente com uma frequência mínima de uma vez por dia;
- Verifique se cada notícia contém um título, uma breve descrição e um link para a leitura de sua íntegra.

## Histórias deste épico:

- #14 ;
- #16

**Comment by brenofranca83** [comment]
Épicos não devem conter critérios de aceitação; apenas as histórias derivadas, por serem concretas, possuem esses critérios.
