### ISSUE TITLE
Épico - Divulgação de cursos

### ISSUE THREAD

**Issue by lucasmartiniano6** [aleseixas/financial_platform#12]
# Nome da história
Divulgação de cursos sobre o mercado financeiro.
## Como
Portal que centraliza cursos de diversas páginas diferentes sobre tópicos relacionados a finanças.
## Eu gostaria de
Receber educação financeira.
## De forma que
Possa tomar decisões conscientes sobre meus investimentos.

## Critérios de aceitação

- Verifique se o curso é feito por um profissional qualificado na área.
- Verifique se o curso está atualizado e coerente com o mercado financeiro atual.

## Histórias desse épico:
#13 
#15 
#17

**Comment by brenofranca83** [comment]
Nesse épico, o papel está incorreto. Deve ser um perfil de usuário e não a própria aplicação.

**Comment by brenofranca83** [comment]
O link #17 parece incorreto, já que é outro épico

**Comment by brenofranca83** [comment]
Nas duas histórias desse épico, vocês focaram no consumo dos cursos apenas. Entretanto, é razoável pensar que se precisa de uma curadoria desses cursos... eles não vão aparecer magicamente para os consumidores.
