### ISSUE TITLE
História - Qualificação dos Cursos

### ISSUE THREAD

**Issue by lucasmartiniano6** [aleseixas/financial_platform#13]
Faz parte de #12 

# Nome da história
Qualificação dos Cursos
## Como
Usuário que acessa o portal de cursos sobre o mercado financeiro.
## Eu gostaria de
Visualizar apenas cursos ministrados por profissionais qualificados, que me forneçam informações precisas e relevantes.
## De forma que
Eu possa confiar na qualidade do conteúdo e aprender com segurança.
## Critérios de aceitação
- Exibe cursos somente se os instrutores tiverem comprovação de experiência ou certificações relevantes.
- Cada curso listado apresenta uma breve descrição do profissional e sua qualificação.
- Se um curso não atende aos critérios de qualificação, ele é removido ou sinalizado como “em análise” até ser avaliado.

**Comment by brenofranca83** [comment]
Dos três critérios de aceite, o primeiro não é testável.
O segundo pode vir a ser se estruturar melhor o que é esperado dessa descrição.
Já o terceiro parece uma consequência para outra funcionalidade.
