### ISSUE TITLE
História - Atualização dos Cursos

### ISSUE THREAD

**Issue by lucasmartiniano6** [aleseixas/financial_platform#15]
Faz parte de #12 
## Nome da história
Atualização dos Cursos

# Como
Usuário que acessa o portal de cursos sobre o mercado financeiro.
# Eu gostaria de
Encontrar apenas cursos com conteúdo atualizado e relevante ao cenário econômico atual.
# De forma que
Eu possa aprender práticas e conceitos que realmente se aplicam ao mercado de hoje.
# Critérios de aceitação:
- Todos os cursos listados exibem a data de sua última atualização.
- Cursos cuja última atualização tenha mais de um ano são sinalizados ou revisados para garantir a relevância.
 - Os cursos incluem uma seção que resume as principais mudanças recentes e tendências do mercado financeiro.

**Comment by brenofranca83** [comment]
Novamente, sobre os critérios de aceite. Pensem como implementar um teste para garantí-los. Isso pode guiar para ver se eles estão vagos. O primeiro está muito bom. O segundo, similar ao da outra história, é um link para outra funcionalidade (revisão de cursos). O terceiro pode ser testável, dependendo como se estrutura essa informação. Caso seja um campo aberto de descrição, complica.
