### ISSUE TITLE
História - Simulação de Estratégias com Base em Dados Históricos

### ISSUE THREAD

**Issue by aleseixas** [aleseixas/financial_platform#21]
Esta história faz parte do épico https://github.com/aleseixas/financial_platform/issues/20
## Nome da história
Simular estratégias com base em dados históricos

## Como
Investidor usuário do robô quantitativo.

## Eu gostaria de
Realizar simulações de estratégias de investimento com base em dados históricos.

## De forma que
Eu possa avaliar o desempenho potencial e os riscos de uma estratégia antes de aplicá-la na minha carteira real.

# Critérios de aceitação
- Verifique se é possível  visualizar métricas como retorno médio e volatilidade ao longo do período simulado.
- Verifique se o o robô utiliza dados históricos reais para o dado período.

**Comment by brenofranca83** [comment]
Isso aqui é claramente um épico que necessita ser quebrado em funções mais específicas. Isso seria projetado, implementado, testado e entregue em 2-4 semanas?
