### ISSUE TITLE
História - Relatório diário

### ISSUE THREAD

**Issue by aleseixas** [aleseixas/financial_platform#22]
Esta história faz parte do épico https://github.com/aleseixas/financial_platform/issues/20
## Nome da história
Relato diário

## Como
Investidor usuário do robô quantitativo.

## Eu gostaria de
Receber um relatório diário de desempenho da minha carteira de investimentos.

## De forma que
Eu possa acompanhar as mudanças e resultados dos meus investimentos, ajudando a tomar decisões informadas de ajuste ou manutenção.

# Critérios de aceitação
- Verifique se é possível acessar e visualizar o histórico de relatórios diários
- Verifique se o relatório inclui o valor total da carteira, retorno diário e variação percentual

**Comment by brenofranca83** [comment]
Como saber se um relatório foi gerado corretamente? Isso deveria estar nos critérios.
