### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Danieldcv** [aleseixas/financial_platform#9]
Tela de login para o usuário entrar na plataforma. Exige que o usuário digite o nome com o qual se cadastrou na plataforma e a senha definida no momento de cadastro. Oferece ao usuário a opção de recriar sua senha, caso ele a esqueça (ainda será implementado). Também oferece ao usuário a opção de ele criar uma nova conta, caso esteja acessando a plataforma pela primeira vez, por exemplo, o que o direciona automaticamente para a tela de cadastro.

**Comment by lucasmartiniano6** [comment]
Ótimo.
